server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info

app:
  dir:
    imgdir: file:///C:\hanaspring\sb2\imgs
    logdir: file:///C:\hanaspring\sb2\logs