server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy

#    url: jdbc:log4jdbc:mysql://172.16.21.91:3306/shopdb?characterEncoding=utf8
#    username: user01
#    password: 111111

    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    username: user02
    password: 12200744

    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul



mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info


app:
  dir:
    imgdir: file:C:/project/imgs/ # => /root/project/imgs 형태로 돌아가게 됨
    logdir: file:C:/project/logs/   #file:///C:\hanaspring\sb2\logs